[package]
name = "face_landmark_mp"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]
edition = "2018"

[dependencies]
nalgebra = "*"
image = "*"
imageproc = "*"

[dev-dependencies]
opencv = "*"
